---
# pretask before running roles

- name: Preflight Check - Fail if can not get ansible distribution
  fail:
    msg: "Ansible cannot determine the ansible_distribution and/or ansible_distribution_version"
  when:
    - (ansible_distribution is not defined) or
      (ansible_distribution_version is not defined)

- name: Preflight Check - Fail if host is not suitable for this benchmark
  fail:
    msg: "This roles is not suitable for operating system with {{ ansible_distribution }} and version {{ ansible_distribution_version }}"
  when:
    - (ansible_distribution not in cis_target_os_distribution) or
      (ansible_distribution_version not in cis_target_os_version )